### PR TITLE
Use text/template instead of ego

### PR DESCRIPTION
**Pull request by iamkevb**
I got frustrated with ego tonight, took a shot a using `text/template` instead. The nice part is that a step is removed, you just build and run your go project, no need to run ego, or keep an ego.go file in the repo. It's easy to call functions from the template which simplifies the some of the complicated bits.

### CODE REVIEW

**Comment by boourns** [comment]
Works for me, not as bad as I expected.  Lets nuke ego from tools.go and go.mod as well?

**Comment by boourns** [comment]
.. ahh, you haven't done model.go.ego yet haha

**Comment by boourns** [comment]
Actually, leave model.go.ego for now.  I think using generics we can reduce the footprint of generated code by 90%, so maybe it's not worth porting right now.

**Comment by iamkevb** [comment]
Started with the easy one for sure.
I'll look at model before I merge this. If we have to keep ego around, we might as well use it everywhere. I pissed around with templates quite a bit this year. Maybe it's not bad.

**Pull request closed without merging**
